[tool.poetry]
name = "awan-llm-api"
version = "0.0.1"
description = ""
authors = ["Yohan Sambin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
